name: Multi Job workflow
on:
  - workflow_dispatch  # manual trigger
  - push  # on push it will trigger
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: greet
        run: echo "welcome to multi job"
      - name: welcome
        run: echo "multi job is open in another window"
